# Generated by Django 4.0.4 on 2022-05-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='explain', max_length=255, null=True)),
                ('date', models.DateField(null=True)),
                ('count', models.IntegerField(null=True)),
                ('before_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
