# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x04test\x1a\x1bgoogle/protobuf/empty.proto\"=\n\x04Test\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12\r\n\x05\x63ount\x18\x04 \x01(\x05\"\x11\n\x0fTestListRequest\"!\n\x13TestRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xed\x01\n\x0eTestController\x12-\n\x04List\x12\x15.test.TestListRequest\x1a\n.test.Test\"\x00\x30\x01\x12\"\n\x06\x43reate\x12\n.test.Test\x1a\n.test.Test\"\x00\x12\x33\n\x08Retrieve\x12\x19.test.TestRetrieveRequest\x1a\n.test.Test\"\x00\x12\"\n\x06Update\x12\n.test.Test\x1a\n.test.Test\"\x00\x12/\n\x07\x44\x65stroy\x12\n.test.Test\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_TEST = DESCRIPTOR.message_types_by_name['Test']
_TESTLISTREQUEST = DESCRIPTOR.message_types_by_name['TestListRequest']
_TESTRETRIEVEREQUEST = DESCRIPTOR.message_types_by_name['TestRetrieveRequest']
Test = _reflection.GeneratedProtocolMessageType('Test', (_message.Message,), {
  'DESCRIPTOR' : _TEST,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.Test)
  })
_sym_db.RegisterMessage(Test)

TestListRequest = _reflection.GeneratedProtocolMessageType('TestListRequest', (_message.Message,), {
  'DESCRIPTOR' : _TESTLISTREQUEST,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.TestListRequest)
  })
_sym_db.RegisterMessage(TestListRequest)

TestRetrieveRequest = _reflection.GeneratedProtocolMessageType('TestRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _TESTRETRIEVEREQUEST,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.TestRetrieveRequest)
  })
_sym_db.RegisterMessage(TestRetrieveRequest)

_TESTCONTROLLER = DESCRIPTOR.services_by_name['TestController']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEST._serialized_start=49
  _TEST._serialized_end=110
  _TESTLISTREQUEST._serialized_start=112
  _TESTLISTREQUEST._serialized_end=129
  _TESTRETRIEVEREQUEST._serialized_start=131
  _TESTRETRIEVEREQUEST._serialized_end=164
  _TESTCONTROLLER._serialized_start=167
  _TESTCONTROLLER._serialized_end=404
# @@protoc_insertion_point(module_scope)
